region: us-east-1

function_name: lambda_bitly
handler: service.handler
role: lambda_api
runtime: python3.8
description: Wrapper around Bitly's URL Shortener service
environment_variables:
  BITLY_GENERIC_ACCESS_TOKEN: ${BITLY_GENERIC_ACCESS_TOKEN}

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.

timeout: 300
memory_size: 128
